import { Task, TaskLog } from '../store/task-store';
import { supabase } from '../utils/supabase';

export const SyncService = {
    // Push all cached local interactions uniquely to the cloud
    async pushAllLocalData(userId: string) {
        if (!userId) return;
        try {
            // 1. Push Gamification Profile 
            const { useGamificationStore } = require('../store/gamification-store');
            const gState = useGamificationStore.getState();
            await this.saveUserProfile(userId, { 
                total_points: gState.xp, 
                level: gState.level, 
                streak_longest: gState.stats.maxStreak,
                streak_current: gState.stats.currentStreak
            });

            // 2. Push Habits & Logs
            const { useTaskStore } = require('../store/task-store');
            const tState = useTaskStore.getState();
            await this.syncHabits(userId, tState.habits);
            await this.syncLogs(userId, tState.logs);

            // 3. Push Custom Groups & Member Data
            const { useGroupsStore } = require('../store/groups-store');
            const grpState = useGroupsStore.getState();

            const myGroups = grpState.groups.filter((g: any) => g.createdBy === userId);
            for (const group of myGroups) {
                await supabase.from('groups').upsert({
                    id: group.id,
                    name: group.name,
                    description: group.description || null,
                    creator_id: userId,
                    invite_code: group.inviteCode,
                    created_at: group.createdAt
                }, { onConflict: 'id' });

                if (group.members && group.members.length > 0) {
                    const membersToSync = group.members.map((m: any) => ({
                        group_id: group.id,
                        user_id: m.userId,
                        role: m.role,
                        joined_at: m.joinedAt
                    }));
                    await supabase.from('group_members').upsert(membersToSync, { onConflict: 'group_id,user_id' });
                }
            }

            const allMyGoals = grpState.groups.flatMap((g: any) => g.goals).filter((goal: any) => goal.createdBy === userId);
            if (allMyGoals.length > 0) {
                const goalsToSync = allMyGoals.map((goal: any) => ({
                    id: goal.id,
                    group_id: goal.groupId,
                    creator_id: userId,
                    title: goal.title,
                    description: goal.description || null,
                    icon: goal.icon || null,
                    deadline: goal.deadline || null,
                    created_at: goal.createdAt
                }));
                await supabase.from('group_goals').upsert(goalsToSync, { onConflict: 'id' });
            }

            const myCompletions: any[] = [];
            grpState.groups.flatMap((g: any) => g.goals).forEach((goal: any) => {
                goal.completions.forEach((comp: any) => {
                    if (comp.userId === userId) {
                        myCompletions.push({
                            goal_id: goal.id,
                            user_id: userId,
                            completed_at: comp.completedAt
                        });
                    }
                });
            });
            for (const comp of myCompletions) {
                const { error } = await supabase.from('group_goal_completions').insert(comp);
                if (error && error.code !== '23505') { // Ignore unique constraint dupes
                    console.warn('Silent sync error for completions:', error);
                }
            }
        } catch (error) {
            console.error('Error in offline push sync:', error);
        }
    },

    // Save user profile data (Handled by Supabase Auth Triggers mostly, but for manual updates)
    async saveUserProfile(userId: string, data: any) {
        if (!userId) return;
        try {
            const { error } = await supabase
                .from('profiles')
                .update(data)
                .eq('id', userId);
            if (error) throw error;
        } catch (error) {
            console.error('Error syncing profile:', error);
        }
    },

    // Save habits (sync with habits table)
    async syncHabits(userId: string, habits: Task[]) {
        if (!userId) return;
        try {
            // Mapping store task to database habit schema
            const habitsToSync = habits.map(h => ({
                id: h.id.length === 36 ? h.id : null, // must be valid UUID or generated by Postgres
                user_id: userId,
                title: h.title,
                category_id: null, // Avoid inserting string "health" into UUID category_id
                frequency_type: h.frequency,
                duration_minutes: h.durationMinutes,
                is_archived: h.archived,
                created_at: h.createdAt,
                // Add other fields as per schema
            }));

            // Filter out habits that don't have a valid UUID to prevent DB crash
            // (If we use `null` id, Postgres might auto-generate it if the upsert is actually an insert without conflict)
            const validHabits = habitsToSync.filter(h => h.id !== null);

            if (validHabits.length > 0) {
                const { error } = await supabase
                    .from('habits')
                    .upsert(validHabits, { onConflict: 'id' });

                if (error) throw error;
            }
        } catch (error) {
            console.error('Error syncing habits:', error);
        }
    },

    // Save logs
    async syncLogs(userId: string, logs: TaskLog) {
        if (!userId) return;

        try {
            // First fetch existing tasks for this user to map existing task IDs and avoid duplicates
            const { data: existingTasks } = await supabase
                .from('tasks')
                .select('id, habit_id, scheduled_date')
                .eq('user_id', userId);

            const existingMap = new Map<string, string>();
            if (existingTasks) {
                existingTasks.forEach(t => {
                    if (t.scheduled_date) {
                        existingMap.set(`${t.habit_id}_${t.scheduled_date}`, t.id);
                    }
                });
            }

            const upserts = [];

            for (const [date, habitLogs] of Object.entries(logs)) {
                for (const [habitId, status] of Object.entries(habitLogs)) {
                    let taskStatus = 'todo';
                    if (status === true) taskStatus = 'completed';
                    else if (status === 'skipped') taskStatus = 'skipped';
                    else taskStatus = 'todo';

                    const existingId = existingMap.get(`${habitId}_${date}`);

                    const payload: any = {
                        user_id: userId,
                        habit_id: habitId.length === 36 ? habitId : null,
                        scheduled_date: date,
                        status: taskStatus,
                        title: 'Habit Sync',
                        completed_at: taskStatus === 'completed' ? new Date().toISOString() : null,
                    };
                    if (existingId) payload.id = existingId;
                    upserts.push(payload);
                }
            }

            if (upserts.length > 0) {
                const { error } = await supabase
                    .from('tasks')
                    .upsert(upserts, { onConflict: 'id' });

                if (error) {
                    console.error('Supabase syncLogs upsert error:', error);
                }
            }
        } catch (error) {
            console.error('Error syncing logs:', error);
        }
    },

    // Pull data from Supabase
    async pullData(userId: string) {
        if (!userId) return null;
        try {
            const { data: profile } = await supabase
                .from('profiles')
                .select('*')
                .eq('id', userId)
                .single();

            const { data: habits } = await supabase
                .from('habits')
                .select('*')
                .eq('user_id', userId);

            return {
                profile,
                habits: habits || []
            };
        } catch (error) {
            console.error('Error pulling data:', error);
            return null;
        }
    }
};
